name: Build Retype website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.retype/**'

jobs:
  build:
    name: Build Retype site

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - uses: retypeapp/action-build@latest

      - name: Commit build output
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .retype
          git diff --quiet && git diff --staged --quiet || git commit -m "Update Retype build output [skip ci]"
          git push
